services:
  meme_server:
    build: .
    environment:
      - database_url=postgresql+psycopg2://postgres:test@127.0.0.1:5432/memes
      - s3_host=127.0.0.1:9000
      - s3_username=minio99
      - s3_password=minio123
    network_mode: "host"
    depends_on:
      db:
        condition: service_healthy
      s3:
        condition: service_healthy

  
  db:
    image: postgres
    shm_size: 128mb
    network_mode: "host"
    environment:
      POSTGRES_DB: memes
      POSTGRES_PASSWORD: test
    healthcheck:
      test: ["CMD-SHELL", "pg_isready", "-d", "db_prod"]
      interval: 10s
      timeout: 60s
      retries: 5
      start_period: 80s

  adminer:
    network_mode: "host"
    image: adminer
    restart: always
    ports:
      - 8080:8080

  s3:
    network_mode: "host"
    image: minio/minio
    ports:
      - "9000:9000"
      - "9099:9099"
    environment:
      MINIO_ROOT_USER: minio99
      MINIO_ROOT_PASSWORD: minio123
    volumes:
      - ~/minio/data:/data
    command: server --address ":9000" --console-address ":9099" /data
    healthcheck:
      test: ["CMD", "curl", "-I", "http://127.0.01:9000/minio/health/live"]
      interval: 10s
      timeout: 60s
      retries: 5
      start_period: 80s